add todolist code
lorenzoworx/todoListBestPractices pull request #1
Opened 2023-02-27 13:54 UTC by lorenzoworx

Add code from todo list project for peer review to ensure best practices are used

2023-02-27 16:16 UTC, ikoote1 requested changes
Overall, your work is nice and everything is almost perfect. 

- The functionality of the List is ok.
- Nice description.
- Wonderful readme file
- No linter errors

2023-02-27 16:16 UTC, ikoote1 commented on src/modules/crud.js
> +    this.store = new Storage();
The site works very well with a perfect description and readme file.
_But there are some little things which can make it better._

One of the few things which need some checking is, the declaration of an object inside a constructor.

2023-02-27 16:16 UTC, ikoote1 commented on src/style.css
> +.borderBottom { border-bottom: 1px solid #ccc; }
I really appreciate the way you style your project, the output is very nice. but If it's ok with you. I would suggest that you use some contest properties for better CSS code. 

Thanks for the nice work.

2023-02-28 03:44 UTC, ikoote1 approved these changes
project Approved.

Thanks for working on all the requested changes. Now you are good to go.

2023-02-28 12:17 UTC, merged

2023-02-28 12:19 UTC, lorenzoworx commented on src/style.css
> +.borderBottom { border-bottom: 1px solid #ccc; }
Duly noted